---
- name: image building dependence
  dnf:
    name:
      - curl
      - expect
      - sed
      - tar
      - qemu-kvm
      - virt-install
      - libvirt-daemon-kvm
    state: latest
  become: yes
  register: dnf_result
  until: dnf_result is success
  retries: 5
  delay: 60

- name: generate kickstart file for ami
  template:
    src: "{{ os }}-{{ cloud_platform }}-ks-cfg.j2"
    dest: "/home/fedora/{{ os }}_{{ arch }}.ks"
  when:
    - cloud_platform == "aws"

- name: generate kickstart file for openstack image
  template:
    src: "rhel-8-{{ cloud_platform }}-ks-cfg.j2"
    dest: "/home/fedora/{{ os }}_{{ arch }}.ks"
  when:
    - cloud_platform == "openstack" or cloud_platform == "gcp"

- name: generate virt-install-image shell script
  template:
    src: "virt-install-image.j2"
    dest: "/home/fedora/virt-install-image"
    mode: '0764'

- name: build qcow2 image first
  command: /home/fedora/virt-install-image /home/fedora/{{ os }}_{{ arch }}.qcow2 {{ os }}_{{ arch }}.ks {{ repos[os][arch]["baseos"] }}

- name: "convert qcow2 to {{ image_type[cloud_platform] }}"
  command: qemu-img convert -O {{ image_type[cloud_platform] }} /home/fedora/{{ os }}_{{ arch }}.qcow2 /home/fedora/{{ os }}_{{ arch }}.{{ image_type[cloud_platform] }}
  when: cloud_platform == "azure"

- name: "convert {{ os }}_{{ arch }}.qcow2 to raw"
  command: /usr/bin/qemu-img convert -O raw /home/fedora/{{ os }}_{{ arch }}.qcow2 /home/fedora/disk.raw
  when: cloud_platform == "gcp"

# archive module does not support --format=oldgnu which is required by GCP
# https://cloud.google.com/compute/docs/import/import-existing-image#requirements_for_the_image_file
- name: compress raw to .tar.gz
  command: tar --format=oldgnu -Sczf {{ os }}_{{ arch }}.tar.gz disk.raw
  args:
    chdir: /home/fedora
  when: cloud_platform == "gcp"

- name: fetch image back
  fetch:
    src: "/home/fedora/{{ os }}_{{ arch }}.{{ image_type[cloud_platform] }}"
    dest: "{{ playbook_dir }}/"
    validate_checksum: yes
    flat: yes
