---
- name: image building dependence
  dnf:
    name:
      - curl
      - expect
      - sed
      - tar
      - qemu-kvm
      - virt-install
      - libvirt-daemon-kvm
    state: latest
  become: yes
  register: dnf_result
  until: dnf_result is success
  retries: 5
  delay: 60

- name: generate kickstart file
  template:
    src: "{{ os }}-{{ cloud_platform }}-ks-cfg.j2"
    dest: "/home/fedora/{{ os }}_{{ arch }}.ks"

- name: generate virt-install-image shell script
  template:
    src: "virt-install-image.j2"
    dest: "/home/fedora/virt-install-image"
    mode: '0764'

- name: build qcow2 image first
  command: /home/fedora/virt-install-image /home/fedora/{{ os }}_{{ arch }}.qcow2 {{ os }}_{{ arch }}.ks {{ repos[os][arch]["baseos"] }}

- name: "convert qcow2 to {{ image_type[cloud_platform] }}"
  command: qemu-img convert -O {{ image_type[cloud_platform] }} /home/fedora/{{ os }}_{{ arch }}.qcow2 /home/fedora/{{ os }}.{{ image_type[cloud_platform] }}
  when: cloud_platform == "azure"

- name: fetch image back
  fetch:
    src: "/home/fedora/{{ os }}_{{ arch }}.{{ image_type[cloud_platform] }}"
    dest: "{{ playbook_dir }}/"
    validate_checksum: yes
    flat: yes
