---
- name: image building dependence
  dnf:
    name:
      - curl
      - expect
      - sed
      - tar
      - qemu-kvm
      - virt-install
      - libvirt-daemon-kvm
    state: latest
  become: yes
  register: dnf_result
  until: dnf_result is success
  retries: 5
  delay: 60

- name: generate kickstart file for ami
  template:
    src: "{{ os }}-{{ cloud_platform }}-ks-cfg.j2"
    dest: "/home/fedora/{{ os }}_{{ arch }}.ks"
  when:
    - cloud_platform == "aws"

- name: "generate kickstart file for {{ cloud_platform }} {{ os }} image"
  template:
    src: "rhel-8-{{ cloud_platform }}-ks-cfg.j2"
    dest: "/home/fedora/{{ os }}_{{ arch }}.ks"
  when:
    - "'rhel-8' in os"
    - cloud_platform == "openstack" or cloud_platform == "gcp" or cloud_platform == "azure"

- name: "generate kickstart file for {{ cloud_platform }} {{ os }} image"
  template:
    src: "rhel-9-{{ cloud_platform }}-ks-cfg.j2"
    dest: "/home/fedora/{{ os }}_{{ arch }}.ks"
  when:
    - "'rhel-9' in os"
    - cloud_platform == "openstack" or cloud_platform == "gcp" or cloud_platform == "azure"

- name: generate virt-install-image shell script
  template:
    src: "virt-install-image.j2"
    dest: "/home/fedora/virt-install-image"
    mode: '0764'

- name: build qcow2 image first
  command: /home/fedora/virt-install-image /home/fedora/{{ os }}_{{ arch }}.qcow2 {{ os }}_{{ arch }}.ks {{ repos[os][arch]["baseos"] }}

- name: "convert qcow2 to {{ image_type[cloud_platform] }}"
  shell: |
    qemu-img convert -f qcow2 -O raw /home/fedora/{{ os }}_{{ arch }}.qcow2 /home/fedora/{{ os }}_{{ arch }}.raw
    MB=$((1024*1024))
    size=$(qemu-img info -f raw --output json /home/fedora/{{ os }}_{{ arch }}.raw | gawk 'match($0, /"virtual-size": ([0-9]+),/, val) {print val[1]}')
    rounded_size=$((($size/$MB + 1)*$MB))
    qemu-img resize -f raw /home/fedora/{{ os }}_{{ arch }}.raw $rounded_size
    qemu-img convert -f raw -o subformat=fixed,force_size -O vpc /home/fedora/{{ os }}_{{ arch }}.raw /home/fedora/{{ os }}_{{ arch }}.{{ image_type[cloud_platform] }}
  when: cloud_platform == "azure"

- name: "convert {{ os }}_{{ arch }}.qcow2 to raw"
  command: /usr/bin/qemu-img convert -O raw /home/fedora/{{ os }}_{{ arch }}.qcow2 /home/fedora/disk.raw
  when: cloud_platform == "gcp"

# archive module does not support --format=oldgnu which is required by GCP
# https://cloud.google.com/compute/docs/import/import-existing-image#requirements_for_the_image_file
- name: compress raw to .tar.gz
  command: tar --format=oldgnu -Sczf {{ os }}_{{ arch }}.tar.gz disk.raw
  args:
    chdir: /home/fedora
  when: cloud_platform == "gcp"

- name: fetch image back
  fetch:
    src: "/home/fedora/{{ os }}_{{ arch }}.{{ image_type[cloud_platform] }}"
    dest: "{{ playbook_dir }}/"
    validate_checksum: yes
    flat: yes
