---
- name: random number as part of instance name
  set_fact:
    random_number: "{{ 99 | random(start=11) }}"

- name: create a new openstack keypair
  openstack.cloud.keypair:
    cloud: rhos-01
    state: present
    name: kite-test
    public_key_file: key/identity.pub

- name: create security group
  openstack.cloud.security_group:
    cloud: rhos-01
    name: kite-test
    state: present
    description: security group for kite image build server

- name: set ssh rule for security group kite-test
  openstack.cloud.security_group_rule:
    cloud: rhos-01
    security_group: kite-test
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- name: set openstack instance name
  set_fact:
    instance_name: "kite-image-builder-{{ os }}-{{ random_number }}"

- name: deploy instance
  openstack.cloud.server:
    cloud: rhos-01
    name: "{{ instance_name }}"
    image: "{{ images['fedora-34'] }}"
    flavor: "{{ flavor }}"
    network: "{{ network }}"
    key_name: kite-test
    security_groups: kite-test
    auto_ip: yes
    wait: yes
    timeout: 600
    userdata: |
      #!/bin/bash
      dnf -y install python3-dnf python3
  register: instance_result

- name: waits until instance is reachable
  wait_for:
    host: "{{ instance_result.openstack.public_v4 }}"
    port: 22
    search_regex: OpenSSH
    delay: 10

- name: add os instance ip into host group builder
  add_host:
    name: "{{ instance_result.openstack.public_v4 }}"
    groups: builder

- name: keep private key permission to 600
  file:
    path: "{{ playbook_dir }}/key/identity"
    mode: "0600"

- name: ensure cloud-init has finished
  raw: test -f /var/lib/cloud/instance/boot-finished
  retries: 60
  register: cloud_init_check
  changed_when: false
  until: cloud_init_check is success
  delegate_to: "{{ instance_result.openstack.public_v4 }}"
